### ISSUE TITLE
Multiple issues with running of script

### ISSUE THREAD

**Issue by ghost** [JBines/Remove-StaleGuests#1]
Some issues I've found:

Line 6 usage says:
`[-ExportCSVPath <String>]`

Line 15 however says
"This is a switch only and the filename will be set via the script"

So Line 6 shouldn't have an optional `<String>` ?

Line 22 usage says:
`Remove-StaleGuests.ps1
-- REPORT ONLY --
In this example the script will provide detailed report information on your guest accounts.`

However line 61 suggests InactiveTimeSpan is Mandatory `    [Parameter(Mandatory = $True)]` so the above usage errors. I've also just ran the script as this example says (no switches so in report mode) and it's made changes:

`Set-NewTimeStamp;CMDlet:Set-MailUser;UPN:...`

Not ideal. No log file either, apart from to console.

I've also installed the latest AzureADPreview (2.0.2.102) and the script test passed the `Test-CommandExists` function however it didn't check and failed on:

`The term 'Get-MailUser' is not recognized as the name of a cmdlet...`

**Comment by JBines** [comment]
Thanks for the feedback! 

Indeed the report only feature needs alittle work or the example should be updated. I'll look at add that as a feature request it's a good point. Thx for the feedback. 

The -ExportCSVPath is indeed not a switch but a string but it will still create a filename will be set via the script (See line 374). 

I should add an example for this. 

Remove-StaleGuests.ps1 -InactiveTimeSpan 365 -ExportCSVPath c:\temp
This will create a csv export of Remove-StaleGuestsyyyyMMddThhmmssZ.csv to c:\temp

Re: Error Test-CommandExists 

You must also connect to EXO as the script will add the lastlogon date to the customattributes to expand the window beyond 90 days.

**Comment by JBines** [comment]
1.0.1 20200617 - JBines - [Feature] Improved default reporting mode, examples and some extra error checking. 

These issues are addressed in this update.
