### ISSUE TITLE
Question regarding this comment that was left halfway

### ISSUE THREAD

**Issue by jonnunez** [JBines/Remove-StaleGuests#11]
```
.PARAMETER InactiveTimeSpan
The InactiveTimeSpan parameter defines the number of days that a guest user has not logged 
using the guest account. Please be aware that the signin data . 

```

What would we need to be aware of?

**Comment by JBines** [comment]
nothing now :) This is from the old ver where the last logon information was based on the audit logs and kept only 90 days of info (unless E5 1 year) so you could have had a bit of a mismatch depending how often you ran the script but the graph now (2020) stores a static last logon value.  Br. Joshua
