### ISSUE TITLE
Unable to see LastLogonDate in Report only mode for initial analysis.

### ISSUE THREAD

**Issue by tolarianNZ** [JBines/Remove-StaleGuests#2]
Terrific script and really well laid out comments within, having a small issue which perhaps is user error (I did read the Readme.md!).  

When I run it in remote only mode (Remove-StaleGuests.ps1 -ExportCSVPath guest.csv) I don't see a column value showing last logon, and using excel to look at the RefreshToken field only runs dates until February this year (but AAD sign in logs will only have last 90 days, and..... 

I see recent LastLogonDate events when running it in (remote-staleguests.ps1 -InactiveTimeSpan 90 -exportcasvpath blah.csv) but without the remove $true, it attempts (I haven't yet elevated to roles capable of making changes, just global/sec reader), it begins to write-host "SUCCESS:  addding lastlogondate to CustomAttribue1".  Which is great, of course it errors hugely because it can't write the attributes but I just did it as a test to see if I misunderstood your instructions.

I need to be able to provide initial stats on how many of our guests are stale, so we can plan the impact of deleting them.  How can I run the script in report only mode, to obtain the LastLogon dates?  Is this possible?

**Comment by JBines** [comment]
Hi @tolarianNZ, thanks for the feedback!

Can you check you are using version 1.0.1 we updated this a couple of weeks ago. (Maybe you have an old copy?) Your csv should have lastlogon value and it should now also be displayed to screen. 

I noted today that it's down to 7 days for free accounts and 30 days for P1 and P2. I'm guessing guest accounts sign in logs will be 7 days :( 

https://docs.microsoft.com/en-us/azure/active-directory/reports-monitoring/reference-reports-data-retention#how-long-does-azure-ad-store-the-data

To get the right results you will need to grant the write access and schedule the script to run each week and wait until you reach the time expiry period.

**Comment by tolarianNZ** [comment]
Thanks for the snappy reply Joshua,

We have 10k AADPP2 licences, and 4.5k guests, I'm keen to know how many are
stale before engaging the hatchet.

I downloaded your script today, used latest AzureAD-Preview ( x.x.2.101
from memory) and the v2 of Exchange Online PS.

I'll check again tomorrow but did not see that CSV column in report mode,
although it piped out to screen.

**Comment by JBines** [comment]
I just reran it now and you should see a lastlogondate in the csv

![image](https://user-images.githubusercontent.com/40031426/86792379-b68d4780-c06a-11ea-95e7-b454b4fa5cc4.png)

**Comment by JBines** [comment]
Hi @tolarianNZ any feedback on this issue?
