### ISSUE TITLE
The request is throttled

### ISSUE THREAD

**Issue by DewREW1989** [JBines/Remove-StaleGuests#3]
Hi,

thanks you for you job. But in environment with 2000 users I've got such as error:

Message: This request is throttled. Please try again after the value specified in the Retry-After header. CorrelationId: XXX
InnerError:
RequestId: YYY
DateTimeStamp: Thu, 6 May 2021 08:00:21 GMT
HttpStatusCode: 429
HttpStatusDescription: Completed
Error occurred while executing GetAuditSignInLogs
Code: UnknownError

and its over and over again. how can I handle with it, please?

**Comment by JBines** [comment]
@DewREW1989  is that 2k of guests or users? It's alittle surprising we have run this on some large orgs without issues. 

Could you try creating a dedicated service account and running it again. If you are using the same account for a number of calls it also could cause an issue. 

I noticed here that over 2000 requests per second are blocked. 

https://docs.microsoft.com/en-us/graph/throttling

**Comment by JBines** [comment]
Lack of update
