### ISSUE TITLE
Remove stale users over 182 days

### ISSUE THREAD

**Issue by Jonroberts84** [JBines/Remove-StaleGuests#4]
I think I'm missing something here, I have read the documentation, and I've run the command "-InactiveTimeSpan 182 -RemoveExpiredGuests:$true" - which has removed expired guest invitations correctly (over 700!) - but I am assuming to remove all guests that haven't been active in 182 days I need to actually capture information for that long, as the Azure logs don't go back that far, so I need to keep running this script to update the time stamps?

According to the last CSV output 1069 out of 1217 haven't logged on at all (but have accepted invitations) and the remainder have logged in within the last 40 days.

Thanks in advance, I'm sure I'm missing something simple, I just don't want to remove users that are still valid.

**Comment by JBines** [comment]
Yes that's right the signing logs are only logged for 90 days so for 180 days you need to run the script at least once per week for 90 days to capture the missing 90 days. 

The good news on this front is that MS have added a static lastlogon date to the Graph API. I haven't tested if this works for guest accounts but I'm hoping we can update this so it will work with a one time run. 

Time is my enemy ATM but hopefully i can have another look soon.

**Comment by Jonroberts84** [comment]
Thanks that's brilliant! The script has helped already to eliminate 700+ expired guest invites, thank you.

**Comment by JBines** [comment]
Really happy to hear it worked as desired 😊 These scripts really are a labour of love but I'm glad we where able to release them publicly to help our fellow engineers!
