### ISSUE TITLE
Too Many Requests

### ISSUE THREAD

**Issue by dfoster3** [JBines/Remove-StaleGuests#7]
Any time I run the script, I get a "Too Many Requests" error from powershell (admin).

`Get-AzureADAuditSignInLogs : Error occurred while executing GetAuditSignInLogs
Code: UnknownError
Message: Too Many Requests
InnerError:
  RequestId: 9740490d-95f4-44f0-910c-90fc06bc2347
  DateTimeStamp: Tue, 08 Feb 2022 22:12:47 GMT
HttpStatusCode: 429
HttpStatusDescription:
HttpResponseStatus: Completed
At C:\scripts\Remove-StaleGuests.ps1:271 char:32
+ ... ogonDate = (Get-AzureADAuditSignInLogs -Top 1  -Filter "userid eq '$g ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-AzureADAuditSignInLogs], ApiException
    + FullyQualifiedErrorId : Microsoft.Open.MSGraphBeta.Client.ApiException,Microsoft.Open.MSGraphBeta.PowerShell.Get
   AuditSignInLogs`

**Comment by JBines** [comment]
Thanks for logging the issue. We are no longer using the `Get-AzureADAuditSignInLogs' CMDlet. 

Please use the updated script which uses the graph API directly

**Comment by dfoster3** [comment]
I should have checked that there was a new version. Thank you!


***@***.***

Dave Foster
IT Administrator
Facilisgroup
Cell: (618) 444-1167<tel:(618)%20444-1167>
www.facilisgroup.com <http://www.facilisgroup.com>
We've moved!
1600 S. Brentwood Blvd - Suite 800, Brentwood, MO 63144
