### ISSUE TITLE
clientId not definded

### ISSUE THREAD

**Issue by BJH74** [JBines/Remove-StaleGuests#8]
Great script JBines,

I found a small bug on line 304:
$Token = Get-MsalToken -clientID **$clientID** -ClientSecret (ConvertTo-SecureString $ClientSecret -AsPlainText -Force) -tenantID $tenantID

 $clientID should be $AppId.

**Comment by JBines** [comment]
Quite right! Not sure how that made it past my testing but thank you very much for the head up! I've updated the code to 2.0.1
