### ISSUE TITLE
Remote Server 403 Forbidden

### ISSUE THREAD

**Issue by dfoster3** [JBines/Remove-StaleGuests#9]
I'm running into an issue where I'm getting an error 403 forbidden when running the script. I am our tenant global admin, have registered an app, assigned an auth certificate with private key, am connected to azureAD and exchangeonline via powershell, and running in elevated powershell. I've looked at the location in the script that is writing the error, but am unsure what is triggering it, or what is causing the 403. Any advice is appreciated.

`[2022-03-01 12:35:36] [DEBUG] :: Correct RBAC Access Confirmed
[2022-03-01 12:35:36] [SUCCESS] :: Authenication via Certificate - Completed!
[2022-03-01 12:35:37] [Error] :: The remote server returned an error: (403) Forbidden.
Write-Log : [2022-03-01 12:35:37] [Error] :: The remote server returned an error: (403) Forbidden.
At C:\scripts\Remove-StaleGuests.ps1:399 char:9
+         Write-Log -Message $ErrorMessage -LogLevel Error -ConsoleOutp ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Write-Log`

**Comment by JBines** [comment]
Hey @dfoster3 , 

Looks like you have missed adding the Graph API permissions on the azure application. 

B
J

IMPORTANT! Hey! Graph API Beta is used. You must use user creds or an Azure Application which is 
granted the following permissions. 
    
    AuditLog.Read.All  - Access LastLogon information
    Directory.Read.All - Fix auditlog bug
    User.ReadWrite.All - Needed for guest removal (Allow only after extensive testing)
    
    Quickstart: https://docs.microsoft.com/en-us/azure/active-directory/develop/quickstart-register-app

**Comment by JBines** [comment]
Btw - you will not need any connections to azure ad or exchange if configured correctly.

**Comment by dfoster3** [comment]
I apologize, I meant to mention this in my previous message - these settings are allowed on the registered app I created. I used the quickstart guide to create the application, I've tried several different options for the reply URI to troubleshoot just in case. This is the powershell command I'm executing, in case I've done something wrong here:

`.\remove-staleguests.ps1 -exportCSVPath "c:\scripts\guestlist.csv" -AppID "XXXXXX" -TenantID "XXXXXX" -CertificatePath "Cert:\CurrentUser\my\HEXSTRING"`

![image](https://user-images.githubusercontent.com/90278327/156414928-3f342139-b0d8-44c8-bde6-bb243aa11b3a.png)

**Comment by dfoster3** [comment]
I changed the permissions from Delegated to Application type and the script is now running. Thanks!

**Comment by JBines** [comment]
great! and thanks for closing the issue :)
